// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace OnlineShopping.Models;

public partial class onlineshopdbContext : DbContext
{
    public onlineshopdbContext()
    {
    }

    public onlineshopdbContext(DbContextOptions<onlineshopdbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Feedbacktbl> Feedbacktbls { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Register> Registers { get; set; }

    public virtual DbSet<Userorder> Userorders { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=myazure.database.windows.net;Initial Catalog=onlineshop;User ID=venom;Password=Pain@117");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Feedbacktbl>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__feedback__3213E83F0D5D7865");

            entity.ToTable("feedbacktbl");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Fstatus).HasColumnName("fstatus");
            entity.Property(e => e.Pid)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("pid");
            entity.Property(e => e.Ratings).HasColumnName("ratings");
            entity.Property(e => e.Usermessage)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("usermessage");
            entity.Property(e => e.Username)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("username");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Pid).HasName("PK__products__DD37D91AC6E2D040");

            entity.ToTable("products");

            entity.Property(e => e.Pid)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("pid");
            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("description");
            entity.Property(e => e.Pimage)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("pimage");
            entity.Property(e => e.Pname)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("pname");
            entity.Property(e => e.Price).HasColumnName("price");
        });

        modelBuilder.Entity<Register>(entity =>
        {
            entity.HasKey(e => e.Uname).HasName("PK__Register__C7D2484F168D34C9");

            entity.ToTable("Register");

            entity.Property(e => e.Uname)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("uname");
            entity.Property(e => e.Country)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("country");
            entity.Property(e => e.Designation)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("designation");
            entity.Property(e => e.Dob)
                .HasColumnType("datetime")
                .HasColumnName("DOB");
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.Gender).HasColumnName("gender");
            entity.Property(e => e.Password)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("password");
        });

        modelBuilder.Entity<Userorder>(entity =>
        {
            entity.HasKey(e => e.Tranid).HasName("PK__userorde__9A599E031C5A5EAD");

            entity.ToTable("userorders");

            entity.Property(e => e.Tranid).HasColumnName("tranid");
            entity.Property(e => e.Pid)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("pid");
            entity.Property(e => e.Qty).HasColumnName("qty");
            entity.Property(e => e.Transdate).HasColumnName("transdate");
            entity.Property(e => e.Username)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("username");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}