// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineShopping.Models;

public partial class Product
{
    public string Pid { get; set; }

    public string Pname { get; set; }

    public string Description { get; set; }

    public int? Price { get; set; }

    public string Pimage { get; set; }
}