// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineShopping.Models;

public partial class Feedbacktbl
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Pid { get; set; }

    public int? Ratings { get; set; }

    public string Usermessage { get; set; }

    public bool? Fstatus { get; set; }
}